# Generated by Django 3.2 on 2023-07-17 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_ingredients_ingredientsamount_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('recipe',), 'verbose_name': 'Список избранного', 'verbose_name_plural': 'Список избранного'},
        ),
        migrations.AlterModelOptions(
            name='ingredientsamount',
            options={'ordering': ('ingredient',), 'verbose_name': 'Количество ингридиент', 'verbose_name_plural': 'Количество ингридиентов'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('recipe',), 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Список покупок'},
        ),
        migrations.AlterField(
            model_name='ingredientsamount',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиентов должно быть больше 0'), django.core.validators.MaxValueValidator(32000, message='Количество ингредиентов не должно быть больше 32000')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления должно быть больше 0'), django.core.validators.MaxValueValidator(32000, message='Время приготовления должно быть не больше 32000')], verbose_name='Время приготовления (в минутах)'),
        ),
    ]
