# Generated by Django 3.2 on 2023-07-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Вы уже подписаны на данного автора',
        ),
    ]
