# Generated by Django 3.2 on 2023-07-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow_вы уже подписаны на данного автора'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['author_id'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
